#!/bin/bash
set -e

# Script to create PR and link to work item
# Usage: create-pr-and-link.sh <org> <project> <repo> <work_item_id> <work_item_title> <creator_email> <branch_name>

ORG="$1"
PROJECT="$2"
REPO="$3"
WORK_ITEM_ID="$4"
WORK_ITEM_TITLE="$5"
CREATOR_EMAIL="$6"
BRANCH_NAME="$7"

SCRIPTS_DIR="$(dirname "$0")"

echo "📬 Creating Pull Request..."

# Read the summary generated by Copilot
if [ -f "copilot-summary.md" ]; then
  PR_DESCRIPTION=$(cat copilot-summary.md)
  echo "✅ Using Copilot-generated PR description"
else
  PR_DESCRIPTION="Automated implementation by GitHub Copilot CLI for Work Item #${WORK_ITEM_ID}"
  echo "⚠️  Using default PR description"
fi

# Get target branch (default to main)
TARGET_BRANCH="main"

# Create PR with required reviewer
PR_OUTPUT=$("$SCRIPTS_DIR/create-pr-with-required-reviewer.sh" \
  "$ORG" \
  "$PROJECT" \
  "$REPO" \
  "$BRANCH_NAME" \
  "$TARGET_BRANCH" \
  "$WORK_ITEM_TITLE" \
  "$PR_DESCRIPTION" \
  "$CREATOR_EMAIL")

PR_ID=$(echo "$PR_OUTPUT" | tail -n 1)
echo "✅ Pull Request created: ID $PR_ID"

# Link PR to work item
echo "🔗 Linking Pull Request to work item..."
"$SCRIPTS_DIR/link-pr-to-workitem.sh" "$WORK_ITEM_ID" "$PROJECT" "$REPO" "$PR_ID"

# Store PR info
echo "##vso[task.setvariable variable=PrId]$PR_ID"
PR_URL="https://dev.azure.com/${ORG}/${PROJECT}/_git/${REPO}/pullrequest/${PR_ID}"
echo "##vso[task.setvariable variable=PrUrl]$PR_URL"

echo "✅ PR created and linked successfully"
echo "🔗 URL: $PR_URL"
