#!/bin/bash
set -e

# Script to post workflow completion comment to GitHub issue
# Usage: post-workflow-comment.sh <issue_number> <pr_url>

ISSUE_NUMBER="$1"
PR_URL="$2"

if [ -z "$ISSUE_NUMBER" ] || [ -z "$PR_URL" ]; then
  echo "❌ Error: Missing required parameters"
  echo "Usage: post-workflow-comment.sh <issue_number> <pr_url>"
  exit 1
fi

if [ -z "$GH_TOKEN" ]; then
  echo "❌ Error: GH_TOKEN environment variable is not set"
  exit 1
fi

echo "💬 Adding completion comment to issue #${ISSUE_NUMBER}..."

COMMENT="## 🎉 Implementation Complete!

The GitHub Copilot CLI has successfully implemented the changes for this issue.

### 📬 Pull Request
A Pull Request has been created with the implementation:
${PR_URL}

### 👀 Next Steps
1. Review the Pull Request
2. Test the implementation
3. Approve and merge if everything looks good

### 📦 Logs
Workflow logs and Copilot execution logs are available in the workflow run artifacts.

---
*This comment was automatically generated by the GitHub Copilot Coder workflow.*"

gh issue comment "$ISSUE_NUMBER" --body "$COMMENT"

echo "✅ Comment added successfully"
